export let scoresValue = new Map([
  ['ones', '-'],
  ['twos', '-'],
  ['threes', '-'],
  ['fours', '-'],
  ['fives', '-'],
  ['sixes', '-'],
  ['bonus', 0],
  ['total', 0],
  ['3 of kind', '-'],
  ['4 of kind', '-'],
  ['full house', '-'],
  ['small straight', '-'],
  ['large straight', '-'],
  ['yahtzee', '-'],
  ['chance', '-'],
  ['grand total', 0],
]);

export let tmpScoresValue = new Map([
  ['ones', 0],
  ['twos', 0],
  ['threes', 0],
  ['fours', 0],
  ['fives', 0],
  ['sixes', 0],
  ['bonus', 0],
  ['total', 0],
  ['3 of kind', 0],
  ['4 of kind', 0],
  ['full house', 0],
  ['small straight', 0],
  ['large straight', 0],
  ['yahtzee', 0],
  ['chance', 0],
  ['grand total', 0],
]); 
